development:
  adapter: postgresql
  encoding: unicode
  database: api_instagator
  host: localhost
  username: api_instagator
  password: 
test:
  adapter: postgresql
  encoding: unicode
  database: api_instagator_test
  host: localhost
  pool: 5
  username: api_instagator
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: api_instagator_production
  pool: 25
  username: api_instagator
  password: